// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelBookingSystem.Models;

public partial class RoomBooking
{
    public int Id { get; set; }

    public int GuestId { get; set; }

    public DateTime CheckIn { get; set; }

    public DateTime CheckOut { get; set; }

    public int NumberOfAdults { get; set; }

    public int? NumberOfChildren { get; set; }

    public virtual Guest Guest { get; set; }

    public virtual ICollection<Room> RoomNumbers { get; set; } = new List<Room>();
}