// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelBookingSystem.Models;

public partial class Room
{
    public int RoomNumber { get; set; }

    public int RoomTypeId { get; set; }

    public virtual ICollection<DailyRoomAvailablity> DailyRoomAvailablities { get; set; } = new List<DailyRoomAvailablity>();

    public virtual RoomType RoomType { get; set; }

    public virtual ICollection<RoomBooking> Bookings { get; set; } = new List<RoomBooking>();
}