// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelBookingSystem.Models;

public partial class Token
{
    public int TokenId { get; set; }

    public int GuestId { get; set; }

    public string TokenValue { get; set; }

    public virtual Guest Guest { get; set; }
}